# Generated by Django 5.2.6 on 2025-09-10 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='course/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('SD', 'Software Development'), ('ML', 'Machine Learning'), ('DS', 'Data Scientist'), ('AI', 'Artificial Inteligence'), ('DP', 'Deep Learning'), ('EH', 'Ethical Hacking')], default='SD', max_length=2)),
            ],
        ),
    ]
