# Generated by Django 5.2.6 on 2025-09-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
