# Generated by Django 5.2.6 on 2025-09-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_coursevariety_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevariety',
            name='price',
            field=models.IntegerField(default=500),
        ),
    ]
